name: Check PullRequest Pattern
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    # Don't run on pull requests from deploy branches as these never have ticket numbers
    # Also don't run on pull requests from dependabot
    if: startsWith(github.head_ref, 'deploy/v') == false && startsWith(github.actor, 'dependabot') == false
    steps:
      - name: Extract Ticket
        run: |
          PR_NUM=$(echo '${{ github.event.pull_request.title }}' | grep -o -P "PAX-I[0-9]+" | head -n 1)
          echo "PR_NUMBER=#$PR_NUM" >> $GITHUB_ENV
        shell: bash
      - name: Update PR Description
        uses: nefrob/pr-description@v1.2.0
        if: ${{ !contains(github.event.pull_request.body, env.PR_NUMBER) }}
        with:
            content: "\n${{ env.PR_NUMBER }}"
            token: ${{ secrets.GITHUB_TOKEN }}
